spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shopee_backend}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:000000}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.shopee.backend: DEBUG

app:
  jwt:
    access-secret-key: ${JWT_ACCESS_SECRET:U2hvcGVlQ2xvbmVBY2Nlc3NTZWNyZXRLZXlGb3JKV1RUZXN0MjAyNg==}
    refresh-secret-key: ${JWT_REFRESH_SECRET:U2hvcGVlQ2xvbmVSZWZyZXNoU2VjcmV0S2V5Rm9ySldUVGVzdDIwMjY=}
    access-token-expiration: 86400000      # 24h
    refresh-token-expiration: 2592000000   # 30 ngày
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    public-url: ${PUBLIC_URL:http://localhost:8080}